spring:
  profiles:
    active: "test"
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: test
  jpa:
    show-sql: true
