FROM mysql:latest
ENV MYSQL_PASSWORD=test
ENV MYSQL_USER=test
ENV MYSQL_DATABASE=test
WORKDIR /usr/migration
COPY migration.sql .
COPY seed.sql .
RUN mysql -u test -p test < migration.sql
RUN mysql -u test -p test < seed.sql
EXPOSE 3306
ENTRYPOINT ["mysqld"]