FROM mysql:latest
ENV MYSQL_PASSWORD test
ENV MYSQL_ROOT_PASSWORD test
ENV MYSQL_USER test
ENV MYSQL_DATABASE test
WORKDIR /usr/migration
ADD migration.test.sql /docker-entrypoint-initdb.d
ADD seed.test.sql /docker-entrypoint-initdb.d
EXPOSE 3306