USE test;

-- citites
INSERT INTO city VALUES 
    (default, "Vespasiano", 20000),
    (default, "São José do Rio Preto", 10000),
    (default, "Mariana", 100000);

-- Hoods
INSERT INTO hood VALUES

    -- Vespasiano hoods

    (1, "Santa Clara", "NORTH", 5000, 1),
    (2, "Santa Mazé", "SOUTH", 3000, 1),
    (3, "Espoleto", "WEST", 10000, 1),
    (4, "Centro", "SOUTH_EAST", 2000, 1),

    -- São José do Rio Preto hoods

    (5, "São Fred", "WEST", 1000, 2),
    (6, "Ragnar", "NORTH", 4000, 2),
    (7, "Rachel", "SOUTH", 5000, 2),

    -- Mariana hoods

    (8 "Centro", "SOUTH_WEST", 30000, 3),
    (9, "Gazé", "EAST", 10000, 3),
    (10, "Fedor", "WEST", 15000, 3),
    (11, "Padre", "NORTH", 10000, 3),
    (12, "Violência", "SOUTH", 15000, 3);

INSERT INTO crime VALUES
    (default, "STEAL", "fez isso e aquilo outro", 1),
    (default, "MURDER", "blablabla", 8),
    (default, "STEAL", "blablabla", 2),
    (default, "STEAL", "blablabla", 10),
    (default, "MURDER", "não sei", 9),
    (default, "OCCURRENCE", "blablabla", 11),
    (default, "MURDER", "roubou ou matou", 6),
    (default, "MURDER", "fez isso e aquilo outro", 5),
    (default, "STEAL", "blablabla", 9),
    (default, "INFRACTION", "blablabla", 11),
    (default, "STEAL", "memhadasdapd", 4),
    (default, "STEAL", "não sei", 11),
    (default, "MURDER", "memhadasdapd", 9),
    (default, "STEAL", "não sei", 11),
    (default, "INFRACTION", "blablabla", 8),
    (default, "STEAL", "não sei", 11),
    (default, "STEAL", "não sei", 1),
    (default, "MURDER", "não sei", 7),
    (default, "MURDER", "fez isso e aquilo outro", 8),
    (default, "INFRACTION", "roubou ou matou", 10),
    (default, "STEAL", "memhadasdapd", 2),
    (default, "STEAL", "memhadasdapd", 6),
    (default, "STEAL", "blablabla", 6),
    (default, "MURDER", "memhadasdapd", 4),
    (default, "OCCURRENCE", "blablabla", 2),
    (default, "MURDER", "fez isso e aquilo outro", 11),
    (default, "OCCURRENCE", "blablabla", 2),
    (default, "MURDER", "blablabla", 10),
    (default, "STEAL", "não sei", 12),
    (default, "OCCURRENCE", "fez isso e aquilo outro", 9),
    (default, "MURDER", "fez isso e aquilo outro", 9),
    (default, "OCCURRENCE", "blablabla", 8),
    (default, "MURDER", "roubou ou matou", 12),
    (default, "STEAL", "blablabla", 4),
    (default, "OCCURRENCE", "roubou ou matou", 5),
    (default, "OCCURRENCE", "memhadasdapd", 10),
    (default, "MURDER", "roubou ou matou", 3),
    (default, "STEAL", "fez isso e aquilo outro", 2),
    (default, "INFRACTION", "memhadasdapd", 10),
    (default, "INFRACTION", "fez isso e aquilo outro", 6),
    (default, "INFRACTION", "fez isso e aquilo outro", 5),
    (default, "STEAL", "não sei", 7),
    (default, "OCCURRENCE", "não sei", 1),
    (default, "OCCURRENCE", "roubou ou matou", 12),
    (default, "INFRACTION", "fez isso e aquilo outro", 2),
    (default, "INFRACTION", "memhadasdapd", 9),
    (default, "INFRACTION", "fez isso e aquilo outro", 10),
    (default, "INFRACTION", "fez isso e aquilo outro", 7),
    (default, "OCCURRENCE", "não sei", 2),
    (default, "OCCURRENCE", "blablabla", 1),
    (default, "STEAL", "fez isso e aquilo outro", 8),
    (default, "MURDER", "não sei", 5),
    (default, "STEAL", "fez isso e aquilo outro", 7),
    (default, "OCCURRENCE", "não sei", 10),
    (default, "INFRACTION", "roubou ou matou", 9),
    (default, "STEAL", "roubou ou matou", 1),
    (default, "OCCURRENCE", "memhadasdapd", 6),
    (default, "OCCURRENCE", "memhadasdapd", 2),
    (default, "OCCURRENCE", "fez isso e aquilo outro", 1),
    (default, "INFRACTION", "fez isso e aquilo outro", 2),
    (default, "STEAL", "não sei", 3),
    (default, "OCCURRENCE", "não sei", 3),
    (default, "STEAL", "não sei", 1),
    (default, "MURDER", "roubou ou matou", 6),
    (default, "INFRACTION", "roubou ou matou", 7),
    (default, "INFRACTION", "roubou ou matou", 9),
    (default, "INFRACTION", "memhadasdapd", 4),
    (default, "OCCURRENCE", "roubou ou matou", 8),
    (default, "MURDER", "memhadasdapd", 10),
    (default, "STEAL", "blablabla", 12),
    (default, "INFRACTION", "não sei", 8),
    (default, "MURDER", "memhadasdapd", 12),
    (default, "INFRACTION", "memhadasdapd", 6),
    (default, "OCCURRENCE", "roubou ou matou", 7),
    (default, "OCCURRENCE", "blablabla", 2),
    (default, "STEAL", "não sei", 12),
    (default, "OCCURRENCE", "não sei", 5),
    (default, "INFRACTION", "não sei", 1),
    (default, "OCCURRENCE", "memhadasdapd", 10),
    (default, "MURDER", "roubou ou matou", 12),
    (default, "INFRACTION", "memhadasdapd", 6),
    (default, "OCCURRENCE", "roubou ou matou", 12),
    (default, "STEAL", "memhadasdapd", 11),
    (default, "STEAL", "fez isso e aquilo outro", 1),
    (default, "INFRACTION", "fez isso e aquilo outro", 7),
    (default, "OCCURRENCE", "não sei", 3),
    (default, "MURDER", "fez isso e aquilo outro", 5),
    (default, "STEAL", "blablabla", 5),
    (default, "OCCURRENCE", "fez isso e aquilo outro", 6),
    (default, "MURDER", "fez isso e aquilo outro", 1),
    (default, "OCCURRENCE", "memhadasdapd", 8),
    (default, "OCCURRENCE", "memhadasdapd", 10),
    (default, "INFRACTION", "fez isso e aquilo outro", 10),
    (default, "MURDER", "roubou ou matou", 6),
    (default, "INFRACTION", "não sei", 3),
    (default, "INFRACTION", "roubou ou matou", 12),
    (default, "STEAL", "roubou ou matou", 8),
    (default, "STEAL", "roubou ou matou", 6),
    (default, "MURDER", "blablabla", 3),
    (default, "STEAL", "roubou ou matou", 10),
    (default, "INFRACTION", "roubou ou matou", 2);